language: c
dist: xenial
git:
  depth: 3
  quiet: true

compiler:
 - gcc
 - clang
env:
 - build_type=debug
 - build_type=release

addons:
  apt:
    sources:
      - sourceline: "ppa:ubuntu-toolchain-r/test"
    packages:
      - ninja-build
      - python3
      - python3-pip
      - nasm

install:
  - pip3 install setuptools meson
  - cd $TRAVIS_BUILD_DIR/ext
  - bash aom.cmd
  - bash dav1d.cmd
  - cd ..
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=$build_type -DBUILD_SHARED_LIBS=OFF -DAVIF_CODEC_AOM=ON -DAVIF_LOCAL_AOM=ON -DAVIF_CODEC_DAV1D=ON -DAVIF_LOCAL_DAV1D=ON ..

script: make
