language: c
config: Release
os: linux
dist: bionic

addons:
  apt:
    update: true
    sources:
      - sourceline: "ppa:ubuntu-toolchain-r/test"
      - sourceline: "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main"
    packages:
      - python3-setuptools ninja-build meson nasm gcc-10 g++-10 clang

before_script:
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  - source $HOME/.cargo/env
  - cd $TRAVIS_BUILD_DIR/ext
  - export MAKEFLAGS=-j$(nproc)
  - bash aom.cmd
  - bash dav1d.cmd
  - bash libgav1.cmd
  - bash rav1e.cmd
  - cd ..
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=$config -DBUILD_SHARED_LIBS=OFF -DAVIF_CODEC_AOM=ON -DAVIF_LOCAL_AOM=ON -DAVIF_CODEC_DAV1D=ON -DAVIF_LOCAL_DAV1D=ON -DAVIF_CODEC_RAV1E=ON -DAVIF_LOCAL_RAV1E=ON -DAVIF_CODEC_LIBGAV1=ON -DAVIF_LOCAL_LIBGAV1=ON -DAVIF_BUILD_EXAMPLES=ON -DAVIF_BUILD_APPS=ON -DAVIF_BUILD_TESTS=ON ..
script:
  - make

jobs:
  include:
  - name: "x64 GCC release"
    env: CC=gcc-10 CXX=g++-10
  - name: "x64 Clang release"
    env: CC=clang CXX=clang++
  - name: "Arm64 GCC release"
    arch: arm64
    env: CC=gcc-10 CXX=g++-10
  - name: "Arm64 Clang release"
    arch: arm64
    env: CC=clang CXX=clang++
  - name: "PowerPC GCC release"
    arch: ppc64le
    env: CC=gcc-10 CXX=g++-10
  - name: "IBM Z GCC release"
    arch: s390x
    env: CC=gcc-10 CXX=g++-10
