name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get install -y ninja-build nasm
        pip3 --disable-pip-version-check install setuptools
        pip3 --disable-pip-version-check install meson
    - uses: actions/checkout@v2
    - name: Setup aom
      run: |
        cd ext
        bash aom.cmd
    - name: Setup dav1d
      run: bash dav1d.cmd
    - name: Setup rav1e
      run: |
        bash rav1e.cmd
        cd ..
    - name: Prepare libavif (cmake)
      run: |
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DAVIF_CODEC_AOM=ON -DAVIF_LOCAL_AOM=ON -DAVIF_CODEC_DAV1D=ON -DAVIF_LOCAL_DAV1D=ON -DAVIF_CODEC_RAV1E=ON -DAVIF_LOCAL_RAV1E=ON
    - name: Build libavif (make)
      run: make
