name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set GCC & G++ 10 compiler (on Linux)
      if: runner.os == 'Linux'
      run: echo "CC=gcc-10" >> $GITHUB_ENV && echo "CXX=g++-10" >> $GITHUB_ENV
    - uses: actions/setup-python@v2

    - name: Cache external dependencies
      id: cache-ext
      uses: actions/cache@v2
      with:
        path: ext
        key: ${{ runner.os }}-${{ hashFiles('ext/*.cmd') }}
    - uses: seanmiddleditch/gha-setup-ninja@v3
      if: steps.cache-ext.outputs.cache-hit != 'true'
    - name: Build libyuv
      if: steps.cache-ext.outputs.cache-hit != 'true'
      working-directory: ./ext
      run: bash libyuv.cmd

    - name: Prepare libavif (cmake)
      run: |
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DAVIF_LOCAL_LIBYUV=ON -DAVIF_BUILD_TESTS=0
    - name: Build libavif (make)
      working-directory: ./build
      run: make -j $(($(nproc) + 1))
    - name: Run AVIF Tests (on Linux)
      if: runner.os == 'Linux'
      working-directory: ./build
      run: ./aviftest ../tests/data

