name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Setup rav1e
      working-directory: ./ext
      run: bash rav1e.cmd
    - name: Prepare libavif (cmake)
      run: |
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DAVIF_CODEC_RAV1E=ON -DAVIF_LOCAL_RAV1E=ON -DAVIF_BUILD_TESTS=1
    - name: Build libavif (make)
      working-directory: ./build
      run: make -j $(($(nproc) + 1))
    - name: Run AVIF Tests
      working-directory: ./build
      run: ./aviftest ../tests/data
